services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    volumes:
      - daily-blog-mongo-data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 136910Mg
    networks:
      - daily-blog-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 136910Mg
      ME_CONFIG_MONGODB_URL: mongodb://root:136910Mg@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - daily-blog-network

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    networks:
      - daily-blog-network

  redis-commander:
    image: rediscommander/redis-commander
    container_name: redis-commander
    ports:
      - '8082:8081'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - daily-blog-network

volumes:
  daily-blog-mongo-data:

networks:
  daily-blog-network:
    driver: bridge
